steps:
  - name: 'adoptopenjdk/openjdk8'
    entrypoint: '/workspace/gradlew'
    args: ['jib', '-Djib.to.image=gcr.io/$PROJECT_ID/$REPO_NAME', '-Djib.to.credHelper=gcr']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'run', 'deploy', '$REPO_NAME', '--image=gcr.io/$PROJECT_ID/$REPO_NAME', '--platform=managed']
